#### For instance not accessible and should be run locally


# name: Vault Secrets Test

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   vaulttest:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up environment
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y curl jq

#       - name: Retrieve secret from Vault
#         env:
#           VAULT_ADDR: http://10.10.10.1:8200
#           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
#         run: |
#           echo "Retrieving secret from Vault..."
#           VAULT_SECRET=$(curl --header "X-Vault-Token:$VAULT_TOKEN" $VAULT_ADDR/v1/kv/hello | jq -r '.data.value')
#           echo "The secret value is: $VAULT_SECRET"

#       - name: Save secret to cypress.env.json
#         run: |
#           echo "{\"SECRET\": \"$VAULT_SECRET\"}" > cypress.env.json
#           cat cypress.env.json
